# Forward requests to /legacy if the browser sends a cookie 
# named `is_legacy` or `my_other_cookie`
[[redirects]]
 from = "/api/"
to = "https://blogbackend-z08y.onrender.com:splat"
status = 200
force = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

  [[headers]]
for = "/"
[headers.values]
Access-Control-Allow-Origin = "*"